-- 在 Supabase SQL Editor 中执行此脚本
-- 创建评价表 + 存储桶策略

-- 1. 评价表
CREATE TABLE IF NOT EXISTS evaluations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    q1_meet     VARCHAR(50)  NOT NULL,
    q1_meet_custom TEXT,
    q2_relation VARCHAR(50)  NOT NULL,
    q2_relation_custom TEXT,
    q3_first_impression TEXT,
    q4_personality      TEXT,
    q5_message          TEXT,
    photo_url   TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- 2. 允许已登录用户插入
ALTER TABLE evaluations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_authenticated_insert"
    ON evaluations FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

-- 3. 允许管理员读取全部
CREATE POLICY "allow_admin_select"
    ON evaluations FOR SELECT
    TO authenticated
    USING (auth.email() = 'admin@thu.edu.cn');

-- 4. 存储桶（在 Supabase 控制台 Storage 中手动创建 eval-photos 桶，设为 public）
--    然后执行以下策略：
-- INSERT INTO storage.buckets (id, name, public) VALUES ('eval-photos', 'eval-photos', true)
-- ON CONFLICT (id) DO NOTHING;

-- CREATE POLICY "allow_photo_upload"
--     ON storage.objects FOR INSERT
--     TO authenticated
--     WITH CHECK (bucket_id = 'eval-photos');

-- CREATE POLICY "allow_photo_read"
--     ON storage.objects FOR SELECT
--     TO public
--     USING (bucket_id = 'eval-photos');
